name: telegram_clone_mobile
description: Telegram Clone Mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0

  # state management
  provider: ^6.0.2

  vibration: 1.7.4-nullsafety.0
  flutter_form_builder: ^7.1.1
  shared_preferences: ^2.0.13

  # graphics
  lottie: ^1.2.2

  # firebase
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf