name: telegram_clone_mobile
description: Telegram Clone Mobile application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Injection of Container
  provider: ^5.0.0
  get_it: ^7.1.3

  vibration: 1.7.4-nullsafety.0
  flutter_form_builder: ^6.0.1
  shared_preferences: ^2.0.5

  # graphics
  lottie: ^1.0.1

  # firebase
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  cloud_firestore: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf